import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import Link from "next/link";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Css Demo</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1>Css for Javascript Developers</h1>

        <div>
          <h4>Table of Contents</h4>
          <Link href="/next-home-page">Rendering Logic 1</Link>
          <Link href="/next-home-page">Rendering Logic 2</Link>
          <Link href="/next-home-page">Modern Component Architecture</Link>
          <Link href="/next-home-page">Flexbox</Link>
        </div>
      </main>
    </div>
  );
}
