import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import Link from "next/link";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Css Demo</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1>Css for Javascript Developers</h1>

        <div>
          <h4>Table of Contents</h4>
          <ul className={styles.nobullet}>
            <li>
            <Link href="/modules/rendering-one">Rendering Logic 1</Link>
            </li>
            <li>
            <Link href="/modules/rendering-two">Rendering Logic 2</Link>
            </li>
            <li>
            <Link href="/modules/modern-architecture">
              Modern Component Architecture
            </Link>
            </li>
            <li>
            <Link href="/modules/flex">Flexbox</Link>
            </li>
          </ul>
        </div>
      </main>
    </div>
  );
}
